# Homework 2 - Berkeley STAT 157

Handout 1/29/2019, due 2/5/2019 by 4pm in Git by committing to your repository.

In [63]:
from mxnet import nd, autograd, gluon
import numpy as np

# 1. Multinomial Sampling

Implement a sampler from a discrete distribution from scratch, mimicking the function `mxnet.ndarray.random.multinomial`. Its arguments should be a vector of probabilities $p$. You can assume that the probabilities are normalized, i.e. tha they sum up to $1$. Make the call signature as follows:

```
samples = sampler(probs, shape) 

probs   : An ndarray vector of size n of nonnegative numbers summing up to 1
shape   : A list of dimensions for the output
samples : Samples from probs with shape matching shape
```

Hints:

1. Use `mxnet.ndarray.random.uniform` to get a sample from $U[0,1]$.
1. You can simplify things for `probs` by computing the cumulative sum over `probs`.

In [116]:
def sampler(probs, shape):
    ## Add your codes here
    ret=nd.zeros(shape=shape)
    m, n=shape
    num=1000000
    y=nd.random.uniform(shape=shape)
    print(y)
    x=nd.zeros(shape=n)
    for i in range(m):
        for j in range(n):
            x1=y[i]<probs[:j+1].sum() 
            x2=y[i]>probs[:j].sum()
            for k in range(n):
                if x1[k]==1 and x2[k]==1:
                    x[k]=1
                else:
                    x[k]=0
            print(x)
            ret[i, j]+=x.sum()
    ret/=n
    return ret

# a simple test
sampler(nd.array([0.2, 0.3, 0.5]), (2,3))


[[0.95279163 0.45612976 0.68748826]
 [0.48340863 0.21550767 0.78873944]]
<NDArray 2x3 @cpu(0)>

[0. 0. 0.]
<NDArray 3 @cpu(0)>

[0. 1. 0.]
<NDArray 3 @cpu(0)>

[1. 0. 1.]
<NDArray 3 @cpu(0)>

[0. 0. 0.]
<NDArray 3 @cpu(0)>

[1. 1. 0.]
<NDArray 3 @cpu(0)>

[0. 0. 1.]
<NDArray 3 @cpu(0)>



[[0.         0.33333334 0.6666667 ]
 [0.         0.6666667  0.33333334]]
<NDArray 2x3 @cpu(0)>

# 2. Central Limit Theorem

Let's explore the Central Limit Theorem when applied to text processing. 

* Download [https://www.gutenberg.org/ebooks/84](https://www.gutenberg.org/files/84/84-0.txt) from Project Gutenberg 
* Remove punctuation, uppercase / lowercase, and split the text up into individual tokens (words).
* For the words `a`, `and`, `the`, `i`, `is` compute their respective counts as the book progresses, i.e. 
    $$n_\mathrm{the}[i] = \sum_{j = 1}^i \{w_j = \mathrm{the}\}$$
* Plot the proportions $n_\mathrm{word}[i] / i$ over the document in one plot.
* Find an envelope of the shape $O(1/\sqrt{i})$ for each of these five words.
* Why can we **not** apply the Central Limit Theorem directly? 
* How would we have to change the text for it to apply? 
* Why does it still work quite well?

In [22]:
filename = gluon.utils.download('https://www.gutenberg.org/files/84/84-0.txt')
with open(filename, encoding='utf-8') as f:
    book = f.read()
print(book[0:100])

## Add your codes here


Project Gutenberg's Frankenstein, by Mary Wollstonecraft (Godwin) Shelley

This eBook is for the use


## 3. Denominator-layout notation

We used the numerator-layout notation for matrix calculus in class, now let's examine the denominator-layout notation.

Given $x, y\in\mathbb R$, $\mathbf x\in\mathbb R^n$ and $\mathbf y \in \mathbb R^m$, we have

$$
\frac{\partial y}{\partial \mathbf{x}}=\begin{bmatrix}
\frac{\partial y}{\partial x_1}\\
\frac{\partial y}{\partial x_2}\\
\vdots\\
\frac{\partial y}{\partial x_n}
\end{bmatrix},\quad 
\frac{\partial \mathbf y}{\partial {x}}=\begin{bmatrix}
\frac{\partial y_1}{\partial x}, 
\frac{\partial y_2}{\partial x}, 
\ldots,
\frac{\partial y_m}{\partial x}
\end{bmatrix}
$$

and 

$$
\frac{\partial \mathbf y}{\partial \mathbf{x}}
=\begin{bmatrix}
\frac{\partial \mathbf y}{\partial {x_1}}\\
\frac{\partial \mathbf y}{\partial {x_2}}\\
\vdots\\
\frac{\partial \mathbf y}{\partial {x_3}}\\
\end{bmatrix}
=\begin{bmatrix}
\frac{\partial y_1}{\partial x_1}, 
\frac{\partial y_2}{\partial x_1},
\ldots,
\frac{\partial y_m}{\partial x_1}
\\ 
\frac{\partial y_1}{\partial x_2},
\frac{\partial y_2}{\partial x_2},
\ldots,
\frac{\partial y_m}{\partial x_2}\\ 
\vdots\\
\frac{\partial y_1}{\partial x_n},
\frac{\partial y_2}{\partial x_n},
\ldots,
\frac{\partial y_m}{\partial x_n}
\end{bmatrix}
$$

Questions: 

1. Assume $\mathbf  y = f(\mathbf u)$ and $\mathbf u = g(\mathbf x)$, write down the chain rule for $\frac {\partial\mathbf  y}{\partial\mathbf x}$
2. Given $\mathbf X \in \mathbb R^{m\times n},\ \mathbf w \in \mathbb R^n, \ \mathbf y \in \mathbb R^m$, assume $z = \| \mathbf X \mathbf w - \mathbf y\|^2$, compute $\frac{\partial z}{\partial\mathbf w}$.

Answers:

1. $\frac{\partial \mathbf y}{\partial \mathbf x}=\frac{\partial \mathbf y}{\partial \mathbf u}\frac{\partial \mathbf u}{\partial \mathbf x}$
2. Suppose $\mathbf u=\mathbf X\mathbf w-\mathbf y$, $\mathbf v=\mathbf X\mathbf w$, then
$$
\frac{\partial z}{\partial \mathbf w}=\frac{\partial z}{\partial \mathbf u}\frac{\partial \mathbf u}{\partial \mathbf v}\frac{\partial \mathbf v}{\partial \mathbf w}
$$
where
$$
z=\Vert \mathbf u\Vert^2, \mathbf u=\mathbf v-\mathbf y, \mathbf v=\mathbf X\mathbf w\\
\frac{\partial z}{\partial \mathbf u}=2\mathbf u^\top\\
\frac{\partial \mathbf u}{\partial \mathbf v}=\mathbf I-\frac{\partial \mathbf y}{\partial \mathbf v}=\mathbf I\\
\frac{\partial \mathbf v}{\partial \mathbf w}=\mathbf X
$$
Therefore
$$
\frac{\partial z}{\partial \mathbf w}=2(\mathbf X\mathbf w-\mathbf y)^\top\mathbf X
$$

## 4. Numerical Precision

Given scalars `x` and `y`, implement the following `log_exp` function such that it returns a numerically stable version of 
$$-\log\left(\frac{e^x}{e^x+e^y}\right)$$

In [50]:
def log_exp(x, y):
    ## add your solution here
    return -nd.log(1/(1+nd.exp(y-x)))

Test your codes with normal inputs:

In [51]:
x, y = nd.array([2]), nd.array([3])
z = log_exp(x, y)
z


[1.3132616]
<NDArray 1 @cpu(0)>

Now implement a function to compute $\partial z/\partial x$ and $\partial z/\partial y$ with `autograd`

In [52]:
def grad(forward_func, x, y): 
    x.attach_grad()
    y.attach_grad()
    with autograd.record():
        z=forward_func(x, y)
    z.backward()
    print('x.grad =', x.grad)
    print('y.grad =', y.grad)

Test your codes, it should print the results nicely. 

In [53]:
grad(log_exp, x, y)

x.grad = 
[-0.7310586]
<NDArray 1 @cpu(0)>
y.grad = 
[0.7310586]
<NDArray 1 @cpu(0)>


But now let's try some "hard" inputs

In [54]:
x, y = nd.array([50]), nd.array([100])
grad(log_exp, x, y)

x.grad = 
[-0.]
<NDArray 1 @cpu(0)>
y.grad = 
[0.]
<NDArray 1 @cpu(0)>


Does your code return correct results? If not, try to understand the reason. (Hint, evaluate `exp(100)`). Now develop a new function `stable_log_exp` that is identical to `log_exp` in math, but returns a more numerical stable result.

In [55]:
def stable_log_exp(x, y):
    ## Add your codes here
    if x>y:
        return -nd.log(1/(1+nd.exp(y-x)))
    else:
        return -nd.log(nd.exp(x-y)/(1+nd.exp(x-y)))
grad(stable_log_exp, x, y)

x.grad = 
[-1.]
<NDArray 1 @cpu(0)>
y.grad = 
[1.]
<NDArray 1 @cpu(0)>
